### ISSUE TITLE
Update sponsorship and partners

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-website#1]
We need to make sure that we have IMLS branding on the client pages and a "partners" page with logos on the main site. We've talked about this before, but let's make it a priority before we lose track. I can handle gathering logos if someone will tell me where I should put them.

**Comment by atomrab** [comment]
Ignore the IMLS part of this, already covered here: https://github.com/periodo/periodo-client/issues/115

**Comment by rybesh** [comment]
You can post them here, just attach files to comments. Note that the logos must be vector images, no PNGs, GIFs, JPGs, or TIFFs…

**Comment by rybesh** [comment]
partners thanked here: http://perio.do/contributors/
